name: CI

on:
  pull_request:
    branches: [dev, main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore devops.sln

      - name: Test with coverage
        run: dotnet test MinhaApi.Tests/MinhaApi.Tests.csproj /p:CollectCoverage=true /p:Threshold=80 /p:ThresholdType=line

      - name: Build Docker
        run: docker build -t minhaapi .